In [5]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_excel('Coin_Flip_Probability_Experiment.xlsx')
data.shape

(116, 11)

In [6]:
data.head()

   Unnamed: 0 Groups  ...     Unnamed: 9        Unnamed: 10
0         NaN    NaN  ...  Group average  Group Probability
1         1.0  Grp A  ...           5.22              0.512
2         2.0    NaN  ...            NaN                NaN
3         3.0    NaN  ...            NaN                NaN
4         4.0    NaN  ...            NaN                NaN

[5 rows x 11 columns]

In [7]:
data.columns.str.strip('Expt 1')

Index(['Unnamed: 0', 'Groups', 'Name of the Participants',
       'Record the no. of heads in 10 flips for each experimen', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10'],
      dtype='object')